name: CI - Godot 4

on:
	pull_request:
	push:
		branches:
			- master
	workflow_dispatch:

jobs:
	execute-gut:
		name: Run GUT tests
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
			  uses: actions/checkout@v2

			- name: Docker test
			  uses: ceceppa/godot-gut-ci@main
			  with:
				godot_version: 4.2
