name: CI - Godot 4 with GUT

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
